vich_uploader:
    db_driver: orm
    mappings:
        congreso_images:
            uri_prefix: '%app.path.congreso_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.congreso_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        evento_images:
            uri_prefix: '%app.path.evento_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.evento_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer